# Generated by Django 3.2.7 on 2021-11-26 00:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escolas', '0006_auto_20211105_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpressaoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mRelatorioTitulo', models.CharField(max_length=50)),
                ('mRelatorioSubTitulo', models.CharField(max_length=50)),
                ('mRelatorioEndereco', models.CharField(max_length=50)),
                ('mRelatorioBairro', models.CharField(max_length=50)),
                ('mRelatorioCEP', models.CharField(max_length=8)),
                ('mRelatorioTelefone', models.CharField(max_length=10)),
                ('mRelatorioRamal', models.CharField(max_length=6)),
                ('mRelatorioCidade', models.CharField(max_length=30)),
                ('mRelatorioEmail', models.CharField(max_length=50)),
                ('mRelatorioFoto', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('mRelatorioCopia', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='QSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RelQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('choice', models.CharField(max_length=30)),
                ('orientacoes', models.CharField(max_length=200)),
                ('vencimento', models.DateField(blank=True, default=datetime.datetime.now)),
                ('comentario', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cae_rep', models.CharField(max_length=200)),
                ('escola_rep', models.CharField(max_length=200)),
                ('escola_direcao', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('data_relatorio', models.DateField(default=datetime.datetime.now)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('user_id', models.IntegerField()),
                ('foto_principal', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('foto_1', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('foto_2', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('foto_3', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('foto_4', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('foto_5', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('foto_6', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escolas.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('orientacoes', models.CharField(blank=True, max_length=200)),
                ('vencimento', models.DateField(blank=True, default=datetime.datetime.now)),
                ('comentario', models.CharField(blank=True, max_length=30)),
                ('qsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.qsection')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=30)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.question')),
            ],
        ),
    ]
