# Generated by Django 3.2.7 on 2021-09-20 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('diretor', models.CharField(max_length=200)),
                ('alunos_atendidos_dia', models.CharField(max_length=200)),
                ('total_alunos_matric', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_text', models.CharField(max_length=200)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.escola')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.periodoatendimento')),
            ],
        ),
    ]
