# Generated by Django 3.2.7 on 2021-09-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodoatendimento',
            name='periodo',
        ),
        migrations.AddField(
            model_name='escola',
            name='periodos',
            field=models.CharField(choices=[('manhã', 'MANHÃ'), ('tarde', 'TARDE'), ('noite', 'NOITE'), ('integral', 'INTEGRAL')], default='manhã', max_length=10),
        ),
        migrations.DeleteModel(
            name='ChoiceAtendimento',
        ),
        migrations.DeleteModel(
            name='PeriodoAtendimento',
        ),
    ]
