# Generated by Django 3.2.7 on 2021-09-21 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0002_auto_20210920_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='periodos',
        ),
    ]
