# Generated by Django 3.2.7 on 2021-10-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0003_remove_escola_periodos'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='p_integral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escola',
            name='p_manha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escola',
            name='p_noite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escola',
            name='p_tarde',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escola',
            name='periodos',
            field=models.CharField(choices=[('m', 'Manhã'), ('t', 'Tarde'), ('n', 'Noite'), ('i', 'Integral')], default='m', max_length=1),
        ),
    ]
