# Generated by Django 3.2.7 on 2021-10-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0004_auto_20211002_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='periodos',
        ),
    ]
