# Generated by Django 3.2.7 on 2021-11-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0005_remove_escola_periodos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='p_integral',
            field=models.BooleanField(default=False, verbose_name='Período: Integral'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='p_manha',
            field=models.BooleanField(default=False, verbose_name='Período: Manhã'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='p_noite',
            field=models.BooleanField(default=False, verbose_name='Período: Noite'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='p_tarde',
            field=models.BooleanField(default=False, verbose_name='Período: Tarde'),
        ),
    ]
